env:
    - RUN_ENV=development 
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install maven
language: java
jdk:
    - openjdk7
    - oraclejdk8
script: 
    - sed -e "s#1931861#$PARTNER_ID#g" -e "s#1931861#$PARTNER_ID#g" -e "s#83c3d4449a3abbe92ca5966f5f010eb4#$ADMIN_SECRET#g" -e "s#www.kaltura.com#$API_HOST#g" src/test/resources/test.template.properties > src/test/resources/test.properties
    - ./testAPI/test.sh
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - noam.arad@kaltura.com
      - Elad.cohen@kaltura.com
      - Jonathan.Kanarek@kaltura.com
      - nir.belinky@kaltura.com
    on_success: change
    on_failure: always
